### ISSUE TITLE
Pimcore 5 version ?

### ISSUE THREAD

**Issue by Yivan** [dpfaffenbauer/pimcore-ImportExport#2]
Hello,

We are looking for an extension to import object from CSV on Pimcore 5 and supporting localized field.
Native Pimcore doesn't support localized field and your plugin ImportExport seems to be only Pimcore 4.

Is there a Pimcore 5 version planned ? If not are their alternative GUI import ? (i think to a specific bundle of CoreShop2 maybe which can be installed separatly and support import localized, or other extension ?)

Thanks for your return!

**Comment by dpfaffenbauer** [comment]
Hi Yivan,

have a look at this one: https://github.com/w-vision/ImportDefinitions

This one is not planned to be migrated. The need is too low for that.

Regards

**Comment by Yivan** [comment]
Ha great, i forgot his one! I already tested it (and it is really a great one!), but the name confused me when i was looking for an importer. With the name "ImportDefinition" i was thinking it handle just the definition when i looked fastly on Github for extension ; )) Maybe name could be ImportDefinition&Objects ; ))
(finding a pimcore extension is always not easy as it should be, i hope some dedicated pages on extensions will arrive one day - i know about the one on the Pimcore 5 forum, but a dedicated page on Pimcore website or subdomain will be the top).

You should add a mention to the plugin ImportDefinition for Pimcore5 in the readme from your ImportExport plugin so user will know more easily of it.

By the way, I opened an improvement suggestion on Pimcore:
https://github.com/pimcore/pimcore/issues/2106

**Comment by dpfaffenbauer** [comment]
Glad you like it :)

By the way: The ImportExport Plugin had a different purpose. It was designed to export Objects from a staging env and import/merge data with a Production env. But I don't need it anymore, so its not gonna get ported to Pimcore 5.

**Comment by dpfaffenbauer** [comment]
@Yivan maybe this helps: https://github.com/pimcore/pimcore/issues/2107 ;)
